# Site settings
author: Santiago Salazar Pavajeau
title: Santiago Salazar Pavajeau
header-img: img/home-bg.png
email: santiago.s.pavajeau@gmail.com
copyright_name: Santiago Salazar Pavajeau
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer | React | Redux | JavaScript (ES6) | Node | Postgres
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SantiagoSalazarPavajeau

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
